person:
  firstName: hello
  lastName: world
  age: 20
  boss: false
  birth: 2020/08/11
  email: helloworld@gmail.com
  maps: {k1: v1, k2: v2}
  lists:
    - react
    - springboot
  pet:
    name: snowball
    age: 2
